name: Docker CI

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Dockerhub Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build & Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ../backend
        push: true
        tags: manedurphy/review-service-backend:latest